workflows:
  android-workflow:
    name: Android Build (Debug APK)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: 20
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          # If the android directory exists but gradlew is missing, 
          # we might need to re-add the platform or sync specifically.
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Build Android DEBUG APK
        script: |
          cd android
          # Ensure gradlew exists; if not, generate it using gradle
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk