workflows:
  android-workflow:
    name: Android Build (Debug APK)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: 20
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          # If build.gradle is missing, the android project is incomplete.
          if [ ! -f "android/build.gradle" ]; then
            echo "Android project incomplete. Adding platform..."
            rm -rf android
            npx cap add android
          fi
          npx cap sync android

      - name: Build Android DEBUG APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk