
workflows:
  android-workflow:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play_credentials # If you have these set in Codemagic UI
      node: latest
      ruby: latest
      xcode: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web application
        script: |
          npm run build
      - name: Capacitor Sync
        script: |
          npx cap sync
      - name: Build Android
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email
        notify:
          success: true
          failure: true
