
workflows:
  android-workflow:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play_credentials # If you have these set in Codemagic UI
      node: 22.12.0
      ruby: 3.2.2
      xcode: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web application
        script: |
          npm run build
      - name: Initialize and Sync Capacitor
        script: |
          # Check if android platform is already added, if not add it
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync
      - name: Build Android
        script: |
          cd android
          # Ensure gradlew is executable
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - mypcaccc01@gmail.com # Replace with your email
        notify:
          success: true
          failure: true
